<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <ProjectReference Include="..\WeatherApp.Application\WeatherApp.Application.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.11" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.11" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.11" />
      <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="10.9.0" />
      <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="10.0.11" />
      <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.14.0" />
      <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.11" />
      <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" Version="10.0.11" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Configurations\" />
      <Folder Include="Migrations\" />
    </ItemGroup>

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

</Project>
